# MultiSource/Olden Makefile:  Build all subdirectories automatically

LEVEL = ../../..

## NOTE: This must remain in this order, so that the labels in the nightly 
## tester gnuplot scripts are correct.
PARALLEL_DIRS  := em3d

include $(LEVEL)/Makefile.programs
